spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=atlas
spring.datasource.password=admin12341

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


logging.level.org.springframework.security=DEBUG