server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/atlas_workspace
spring.datasource.username=atlas_workspace
spring.datasource.password=admin1121

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=kVH+0gWYznHzuwUmILDZ0O9RNENaQVbLl++uFj1vcP8=

auth-service.url=http://localhost:8080